//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstandingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Repositories;

    public partial class StudentDetail
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int StudentNumber { get; set; }
        [Required]
        public string Branch { get; set; }
        [Required]
        public string Semester { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }

        StudentRepository objStudentRepository = new StudentRepository();

        #region CreateNewStudent
        public bool CreateNewStudent(StudentDetail objStudentDetail, out int isStudentId)
        {
            int id;
            bool status = objStudentRepository.CreateNewStudent(objStudentDetail, out id);
            if (status == true)
            {
                isStudentId = objStudentDetail.Id;
                return true;
            }
            isStudentId = 0;
            return false;
        }
        #endregion
        #region StudentLogin
        public bool StudentLogin(StudentDetail objStudentDetail,out int isStudentId)
        {
            int id;
            bool status = objStudentRepository.StudentLogin(objStudentDetail, out id);
            if(status==true)
            {
                isStudentId = id;
                return true;
            }
            isStudentId = 0;
            return false;
        }
        #endregion
        #region StudentEditDetail
        public bool StudentEditDetail(StudentDetail objStudentDetail)
        {
            bool status = objStudentRepository.StudentEditDetail(objStudentDetail);
            if(status==true)
            {
                return true;
            }
            return false;
        }
        #endregion
        #region StudentDeleted
        public bool StudentDeleted(StudentDetail objStudentDetail)
        {
            bool status = objStudentRepository.StudentDeleted(objStudentDetail);
            if (status == true)
                return true;
            return false;
        }
        #endregion


    }
}

